function DLCData = addmeanbp( DLCData, meanBP2add )
% ADDMEANBP adds mean body parts to DLC data, e.g., 'head' which is mean of
% snout and ears positions.

for i = 1 : length( meanBP2add )
    bp2add = meanBP2add{ i };
    
    switch bp2add
        case 'head'
            DLCData.( [ bp2add, '_x' ] ) = mean(...
                [ DLCData.snout_x, DLCData.leftear_x, DLCData.rightear_x ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_y' ] ) = mean(...
                [ DLCData.snout_y, DLCData.leftear_y, DLCData.rightear_y ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_likelihood' ] ) = mean(...
                [ DLCData.snout_likelihood, DLCData.leftear_likelihood, DLCData.rightear_likelihood ],...
                2, 'omitnan' );
            
        case { 'body1', 'body' } % include shoulders
            DLCData.( [ bp2add, '_x' ] ) = mean(...
                [ DLCData.shoulders_x, DLCData.midspine_x,...
                DLCData.hips_x, DLCData.tailbase_x ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_y' ] ) = mean(...
                [ DLCData.shoulders_y, DLCData.midspine_y,...
                DLCData.hips_y, DLCData.tailbase_y ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_likelihood' ] ) = mean(...
                [ DLCData.shoulders_likelihood, DLCData.midspine_likelihood,...
                DLCData.hips_likelihood, DLCData.tailbase_likelihood ],...
                2, 'omitnan' );
            
        case 'body2' % don't include shoulders
            DLCData.( [ bp2add, '_x' ] ) = mean(...
                [ DLCData.midspine_x, DLCData.hips_x, DLCData.tailbase_x ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_y' ] ) = mean(...
                [ DLCData.midspine_y, DLCData.hips_y, DLCData.tailbase_y ],...
                2, 'omitnan' );
            DLCData.( [ bp2add, '_likelihood' ] ) = mean(...
                [ DLCData.midspine_likelihood, DLCData.hips_likelihood, DLCData.tailbase_likelihood ],...
                2, 'omitnan' );
            
        otherwise
            error( 'Mean body part must be "head" or "body1" or "body2".' )
            
    end
    
end


end

